### PR TITLE
angular 9 support

### PR DESCRIPTION
**Pull request by mzoabi**
added support for angular 9

### CODE REVIEW

**Comment by Shakur0o** [comment]
@drozhzhin-n-e could you please accept this PR ?

**Comment by drozhzhin-n-e** [comment]
@mzoabi @Shakur0o building the library in ng9 is currently causing problems in earlier versions. But thanks for the update. I merge PR when I figure out how to build libraries with backward compatibility support.

**Comment by doronsever** [comment]
Can you just bump the major version so when people will run npm update they won't be affected if they are on older angular versions?
The thing is that right now your library causing angular not to update without the --force  flag

**Comment by mzoabi** [comment]
upgraded to Angular 9.1

**Comment by drozhzhin-n-e** [comment]
Thanks for the pull request. The app has been updated to version 12

**Pull request closed without merging**
