### PR TITLE
support custom, app-wide, default tooltip-options

### PR DESCRIPTION
**Pull request by mriess260**
currently you must either use the pre-defined default options or re-define custom options for each instance of the tooltip directive.

This allows you to create your custom default options once. The order of priority is maintained:
- Was: custom_instance_options -> default_global_options
- Now: custom_instance_options -> custom_default_options -> default_global_options

### CODE REVIEW

**Comment by drozhzhin-n-e** [comment]
@mriess260 thanks for the help! I will check and add your changes to the branch

**Comment by sks40gb** [comment]
@mriess260  - thanks for It. @drozhzhin-n-e - any Eta on this. We were seeking for this option since long time.

**Comment by drozhzhin-n-e** [comment]
@mriess260 can we leave the possibility for a simple import of the module? For those who do not need to override the default settings.

```
  imports: [
    TooltipModule
  ]
```

**Comment by mriess260** [comment]
I see what you mean; that's probably a good idea. I'll make the change.

**Comment by drozhzhin-n-e** [comment]
@mriess260 great!

**Comment by sks40gb** [comment]
> I see what you mean; that's probably a good idea. I'll make the change.

Did you get the chance to make the changes ?

**Comment by mriess260** [comment]
@drozhzhin-n-e ok, I think it should be good now.

**Comment by sks40gb** [comment]
@mriess260 - There is conflict.

**Comment by mriess260** [comment]
@sks40gb thanks, I was in a rush and didn't think to check

**Comment by drozhzhin-n-e** [comment]
@mriess260 It works, thanks!

**Comment by alisalama** [comment]
Could we have this pushed to npm please?

**Pull request merged**
